#微服务配置
spring:
  profiles:
    active: dev
  application:
    name: system-service
  cloud:
    nacos:
      server-addr: 192.168.101.65:8848
      discovery:
        namespace: dev148
        group: xuecheng-plus-project
      config:
        namespace: dev148
        group: xuecheng-plus-project
        file-extension: yaml
        refresh-enabled: true
        #        共享项目配置
        shared-configs:
          - data-id: logging-${spring.profiles.active}.yaml
            group: xuecheng-plus-common
            refresh: true
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.101.65:3306/xc148_system?serverTimezone=UTC&userUnicode=true&useSSL=false&
#    username: root
#    password: mysql
# 日志文件配置路径
#logging:
#  config: classpath:log4j2-dev.xml


